---

- name: Create or remove zones
  ansible.posix.firewalld:
    zone: "{{ item.name }}"
    permanent: true
    state: "{{ item.state | default('present') }}"
  notify: Reload firewalld
  loop: "{{ firewalld_zones }}"
  loop_control:
    label: "{{ item.name }}"

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Set default firewalld zone
  ansible.builtin.command:
    cmd: "firewall-cmd --set-default-zone={{ firewalld_default_zone }}"
  register: __firewalld_def_zone
  changed_when: '"ZONE_ALREADY_SET" not in __firewalld_def_zone.stderr'
  when: firewalld_default_zone

- name: Configure zone masquarade
  ansible.posix.firewalld:
    zone: "{{ item.name }}"
    masquerade: true
    permanent: true
    state: "{{ item.masquerade | ternary('enabled', 'disabled') }}"
  notify: Reload firewalld
  loop: "{{ firewalld_zones }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - item.state | default('present') == 'present'
    - item.masquerade is defined

- name: Configure zone icmp_block
  ansible.posix.firewalld:
    zone: "{{ item.name }}"
    icmp_block: "{{ item.icmp_block }}"
    permanent: true
    state: "{{ (item.icmp_block_state | default('present') == 'present') | ternary('enabled', 'disabled') }}"
  notify: Reload firewalld
  loop: "{{ firewalld_zones }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - item.state | default('present') == 'present'
    - item.icmp_block is defined

- name: Configure zone icmp_block_inversion
  ansible.posix.firewalld:
    zone: "{{ item.name }}"
    icmp_block_inversion: true
    permanent: true
    state: "{{ item.icmp_block_inversion | ternary('enabled', 'disabled') }}"
  notify: Reload firewalld
  loop: "{{ firewalld_zones }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - item.state | default('present') == 'present'
    - item.icmp_block_inversion is defined

- name: Add zone sources
  ansible.posix.firewalld:
    zone: "{{ item.0.name }}"
    source: "{{ item.1 }}"
    permanent: true
    state: "{{ (item.0.state | default('present') == 'present') | ternary('enabled', 'disabled') }}"
  notify: Reload firewalld
  loop: "{{ firewalld_zones | subelements('sources', skip_missing=True) }}"
  loop_control:
    label: "{{ item.0.name }} - {{ item.1 }}"

- name: Add zone interfaces
  ansible.posix.firewalld:
    zone: "{{ item.0.name }}"
    interface: "{{ item.1 }}"
    permanent: true
    state: "{{ (item.0.state | default('present') == 'present') | ternary('enabled', 'disabled') }}"
  notify: Reload firewalld
  loop: "{{ firewalld_zones | subelements('interfaces', skip_missing=True) }}"
  loop_control:
    label: "{{ item.0.name }} - {{ item.1 }}"

- name: Configure simple services
  ansible.posix.firewalld:
    service: "{{ item.name }}"
    zone: "{{ zone }}"
    permanent: true
    state: "{{ (item.state | default('present') == 'present') | ternary('enabled', 'disabled') }}"
  notify: Reload firewalld
  vars:
    zone: "{{ item.zone | default('public') }}"
  loop: "{{ firewalld_services }}"
  loop_control:
    label: "{{ item.name }} [{{ zone }}]"
  when: item.sources is not defined or item.sources | length == 0

- name: Configure advanced firewalld services  # noqa line-length
  ansible.posix.firewalld:
    zone: "{{ zone }}"
    rich_rule: "rule family={{ item.0.family | default('ipv4') }} source address={{ item.1 }} service name=\"{{ item.0.name }}\" accept"
    permanent: true
    state: "{{ (item.0.state | default('present') == 'present') | ternary('enabled', 'disabled') }}"
  vars:
    zone: "{{ item.0.zone | default('public') }}"
  loop: "{{ firewalld_services | subelements('sources', skip_missing=True) }}"
  loop_control:
    label: "{{ item.0.name }} [{{ zone }}] - {{ item.1 }}"
  notify: Reload firewalld

- name: Configure simple firewalld rules
  ansible.posix.firewalld:
    zone: "{{ item.zone | default('public') }}"
    port: "{{ item.port }}/{{ item.protocol | default('tcp') }}"
    permanent: true
    state: "{{ (item.state | default('present') == 'present') | ternary('enabled', 'disabled') }}"
  loop: "{{ firewall_rules }}"
  notify: Reload firewalld
  when:
    - item.sources is not defined or item.sources | length == 0
    - item.source is not defined or item.source == 'any'

- name: Configure advanced firewalld rules  # noqa line-length
  ansible.posix.firewalld:
    zone: "{{ item.zone | default('public') }}"
    rich_rule: "rule family={{ item.family | default('ipv4') }} source address={{ item.source }} port port={{ item.port }} protocol={{ item.protocol | default('tcp') }} accept"
    permanent: true
    state: "{{ (item.state | default('present') == 'present') | ternary('enabled', 'disabled') }}"
  loop: "{{ firewall_rules }}"
  notify: Reload firewalld
  when:
    - item.sources is not defined or item.sources | length == 0
    - item.source is defined and item.source != 'any'

- name: Configure advanced firewalld rules [multiple sources]  # noqa line-length
  ansible.posix.firewalld:
    zone: "{{ item.0.zone | default('public') }}"
    rich_rule: "rule family={{ item.0.family | default('ipv4') }} source address={{ item.1 }} port port={{ item.0.port }} protocol={{ item.0.protocol | default('tcp') }} accept"
    permanent: true
    state: "{{ (item.0.state | default('present') == 'present') | ternary('enabled', 'disabled') }}"
  loop: "{{ firewall_rules | subelements('sources', skip_missing=True) }}"
  loop_control:
    label: "{{ item.0.port }} - {{ item.1 }}"
  notify: Reload firewalld

- name: Configure firewalld rich rules
  ansible.posix.firewalld:
    zone: "{{ item.zone | default('public') }}"
    rich_rule: "{{ item.rich_rule }}"
    permanent: true
    state: "{{ (item.state | default('present') == 'present') | ternary('enabled', 'disabled') }}"
  loop: "{{ firewalld_rich_rules }}"
  loop_control:
    label: "{{ item.zone }} - {{ item.rich_rule }}"
  notify: Reload firewalld
