---

- name: Install {{ firewall_frontend }}
  ansible.builtin.package:
    name: "{{ firewall_frontend }}"
    state: present
  notify: Start firewall frontend
  when:
    - firewall_frontend
    - firewall_install

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Detect firewall in use
  ansible.builtin.include_tasks: detect.yml
  when: not firewall_frontend

- name: Configure {{ firewall_frontend }}
  ansible.builtin.include_tasks: "{{ firewall_declarative_config | ternary('{{ firewall_frontend }}-declarative.yml', '{{ firewall_frontend }}.yml') }}"
