---

- name: Install {{ firewall_frontend }}
  ansible.builtin.package:
    name: "{{ firewall_frontend }}"
    state: present
  notify: Start firewall frontend
  when:
    - firewall_frontend
    - firewall_install

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Detect firewall in use
  ansible.builtin.include_tasks: detect.yml
  when: not firewall_frontend

- name: Configure firewalld
  ansible.builtin.include_tasks: firewalld.yml
  when: firewall_frontend == "firewalld"

- name: Configure ufw
  ansible.builtin.include_tasks: ufw.yml
  when: firewall_frontend == "ufw"
