---

- name: Prepare
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Update cache and install sudo
      ansible.builtin.package:
        name: sudo
        update_cache: true
        state: present

    - name: Install Debian packages
      ansible.builtin.apt:
        name: procps
        state: present
      when: ansible_os_family == "Debian"

    - name: Install RedHat packages
      ansible.builtin.dnf:
        name: dbus
        state: present
      when: ansible_os_family == "RedHat"

    - name: Ensure dbus is running
      ansible.builtin.systemd:
        name: dbus
        state: started
        enabled: true
      when: ansible_os_family == "RedHat"
