---

on:
  push:
    branches:
      - "master"
      - "main"
      - "v*"
    tags:
      - "v*"

jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install molecule
        run: |
          pip install -U pip wheel setuptools
          pip install 'molecule<5.0' 'ansible-lint<6.20' 'yamllint<1.30' 'jmespath<2.0'
          pip install 'molecule-plugins[podman]<24.0'

      - name: Run molecule
        env:
          ANSIBLE_FORCE_COLOR: 'True'
          PY_COLORS: 'True'
        run: |
          molecule test
